import './globals.css'
import Nav from './components/Nav'
import { getServerSession } from 'next-auth'
import { authOption } from '../pages/api/auth/[...nextauth]'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const Session = await getServerSession(authOption)

  return (
    <html lang="en">

      <body className='mx-64'>
        <Nav user={Session?.user} expires={Session?.expires as string} />
        {children}
      </body>
    </html>
  )
}
